INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (1001, 'USD', 75900);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (1002, 'USD', 40000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (1, 'USD', 10000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (2, 'USD', 20000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (3, 'USD', 30000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (4, 'USD', 40000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (5, 'USD', 50000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (6, 'USD', 60000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (7, 'USD', 70000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (8, 'USD', 80000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (9, 'USD', 90000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (10, 'USD', 100000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (30, 'USD', 1000000);
INSERT INTO PRICE (VEHICLE_ID, CURRENCY, PRICE)
VALUES (40, 'USD', 3000000);